### ISSUE TITLE
Add extractor functions to neotoma

### ISSUE THREAD

**Issue by gavinsimpson** [ropensci/neotoma#141]
The ongoing writing of the neotoma paper has demonstrated to me that the package would benefit from some extractor functions to get parts of the various objects returned by the main functions.
#### Extracting counts from objects

Users need to use constructs like

``` r
western.comp[[1]]$counts
```

to access the counts for the first data set in `western.comp`.

It would be a nicer user experience if they could just do

``` r
counts(western.comp[[1]])
counts(western.comp)
```

The former would return an object of class `c("neo_counts", "data.frame")`, essentially a data frame containing the counts data for that site/ The latter would return an object of class `c("neo_counts_list", "list")`, which would be a list of `neo_counts` objects, one per site/data set in `western.comp`.
#### Extracting sample Ages

This requires

``` r
western.comp[[1]]$sample.meta$Age
```

How about

``` r
ages(western.comp[[1]]) ## or Ages()
ages(western.comp)
```

instead?

This also raises the issue of extracting the sample meta data. That should have an extractor too.

Thoughts?
### List of extractor functions to implement
1. [x] `counts()` to extract count data from objects. Methods for single objects and lists of objects. Track this in Issue #146.
2. [x] `ages()` (or `Ages()`) to extract sample age data from objects. Methods for single objects and lists of objects.
3. [x] `metadata()` to extract forms of metadata from objects. Methods for single objects and lists of objects. Perhaps has argument `type` allowing one to choose which of the sets of metadata is returned.

If you agree that these would be useful and have suggestions for other extractors we should add, list them and I'll add them to the list so we can track progress here for the general issue and have separate issues to track details of each extractor function in more detail.

**Comment by SimonGoring** [comment]
I'm going to close this issue.  The `metadata()` extractor exists as `get_site()` or `get_dataset()`.
