### ISSUE TITLE
Add an extractor function for count data

### ISSUE THREAD

**Issue by gavinsimpson** [ropensci/neotoma#146]
This issue is linked to #141 and relates to an extractor for count data held within neotoma objects.

This issue can be tracked in the [`add-counts-extractor` branch of my fork](https://github.com/gavinsimpson/neotoma/blob/add-counts-extractor/R/counts.R).

**Comment by SimonGoring** [comment]
Gavin, have you made any progress on this?  I was thinking that we could try to add a method for Stratiplot from a `download` object, and make other more explicit links to `analogue`.  Not sure if `neotoma` is the best place for that, or somewhere else, but the extractor function would help.

**Comment by gavinsimpson** [comment]
@SimonGoring yes, but needed to do a bit of fixing up in my [`add-counts-extractor` branch](https://github.com/gavinsimpson/neotoma/blob/add-counts-extractor/R/counts.R) to include all the changes made since we worked on this. Just checking it still works.

**Comment by SimonGoring** [comment]
This issue is resolved.  Counts works nicely.
