### ISSUE TITLE
compile_taxa.R missed.samples object

### ISSUE THREAD

**Issue by andydawson** [ropensci/neotoma#158]
There is an object `missed.samples` in compile_taxa.R that never gets used... not sure what the intention was, but it needs to be fixed or removed.

**Comment by SimonGoring** [comment]
`missed.samples` is used as part of the warning message that is sent out.  That's its only use, but it is used.

**Comment by SimonGoring** [comment]
Oh, I found an extra case of the variable, deleted it, and committed from SimonGoring/neotoma 2acd73e
