### ISSUE TITLE
get_download() bug for Adeline

### ISSUE THREAD

**Issue by andydawson** [ropensci/neotoma#159]
I am getting an error when I run `get_download()` as shown below.

    > site_dat=get_site(sitename="Adeline*")
    The API call was successful, you have returned  1 records.
    > get_download(x=site_dat)
    API call was successful. Returned record for Adeline Lake
    Error in `colnames<-`(`*tmp*`, value = c("taxon.name", "variable.units",  : 
      'names' attribute [8] must be the same length as the vector [1]
    
So far I haven't had problems with others. I'll take a look at this more closely later today.

**Comment by SimonGoring** [comment]
So this was part of a larger issue.  The problem comes from a more inclusive set of datasets than had been previously returned.  The problem should be fixed now.
