### ISSUE TITLE
Command to open site in browser with Neotoma Explorer.

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/neotoma#185]
It should be pretty straightforward, something like:

```r
browse_dataset(datasetid = 7878)
```

should open Neotoma Explorer at [this site](http://apps.neotomadb.org/Explorer/?datasetid=7878).  Presumably using [browseURL](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/browseURL.html).

**Comment by gavinsimpson** [comment]
Why not just `browse()`?

**Comment by SimonGoring** [comment]
That works too.  I'm indifferent, I just want the functionality and wanted
to remind myself to do it.  Simpler is obviously better.

**Comment by gavinsimpson** [comment]
Reasons other than "simpler" include being future proof if you implement as a S3 generic so you can add methods for other functions / data types (of that makes sense), not just a `"dataset"`

**Comment by SimonGoring** [comment]
That is a much better reason, thanks!  I can add those methods right away
anyways. Out of the box it should work with download and dataset objects.

**Comment by SimonGoring** [comment]
This was implemented in commit https://github.com/ropensci/neotoma/commit/6543f7110fa1ffabf3056e1c4b8b4b0fea801134.  Not sure why I missed closing the issue.
