### ISSUE TITLE
travis notifications?  Who's getting them?

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/neotoma#198]
Hi all, now that I'm figuring out the travis stuff a bit better I notice that someone's got integration with slack.  I was going to add my own token as well, but just wanted to check to see who else is linked to it.

@karthik @sckott @gavinsimpson ?

**Comment by gavinsimpson** [comment]
I believe this is an ropensci thing.

**Comment by sckott** [comment]
@SimonGoring yes, commits/issues on this repo go to our slack, as well as travis build reports - i imagine you can add a second notification to go to your slack if you have one

**Comment by SimonGoring** [comment]
Okay, I did and it seemed to work, but I just got a failure notification
from Travis on a build that passed earlier.  Did you get the same one?

**Comment by sckott** [comment]
the last travis notification in our slack is from yesterday from this build https://travis-ci.org/ropensci/neotoma/builds/72153289

**Comment by gavinsimpson** [comment]
The travis build is failing for R code reasons. Quite why `lapply(aa, `[[`, "dataset"]` should throw an error unless the objects in `aa` might not have a `"dataset"` for some some reason is where the problem lies. It might be worth considering adding consistency checks on objects, so that we can throw proper, clear errors if the API returns something we weren't expecting or we missed patching up the object(s) in some cases.

**Comment by gavinsimpson** [comment]
This of course could be a transient issue due to the website or web API being down or acting funky mid-test of course. But we should try to capture those issues too if we can replicate them at all? Probably easier said than done...

**Comment by SimonGoring** [comment]
The weird thing to me is that this exact same build (#99) passed yesterday
at 3:46pm, and is failing now.  it makes me think it's a neotoma API side
problem.

**Comment by gavinsimpson** [comment]
Yes - but indicates we could do better identifying when the API has failed to return something we expected it to do.

**Comment by sckott** [comment]
> we could do better identifying when the API has failed to return something we expected it to do

Is there any unit testing for the API itself?  Or is the testing from this R pkg?

**Comment by SimonGoring** [comment]
Yes, the first set of tests, so it's not that that's causing the bug.  I'll
mess with it later today to see if I can figure out what it is.  A required
package update possibly (overnight?)?

**Comment by SimonGoring** [comment]
I'm closing this issue ('who's getting notifications') and moving the Travis failures over to issue #199.
