### ISSUE TITLE
undefined export read.tilia

### ISSUE THREAD

**Issue by sckott** [ropensci/neotoma#204]
https://travis-ci.org/ropensci/neotoma/builds/112085345#L2033

**Comment by SimonGoring** [comment]
I'm working on this.  The function is half written, it's not supposed to be in the main branch, but it keeps popping up somehow.

**Comment by sckott** [comment]
k, just in case you weren't aware

**Comment by SimonGoring** [comment]
No problem.  I made a mistake a the beginning of writing the file, made a
commit without branching first, then couldn't really reverse it.  That's
why there's a flood of commits now.

On Sun, Feb 28, 2016 at 2:36 PM, Scott Chamberlain <notifications@github.com

**Comment by SimonGoring** [comment]
This issue is resolved with commit https://github.com/ropensci/neotoma/commit/255d60d7501aff3d0db21aa8f6704f3a71fcb6e0.  The `read.tilia` function is finally added, rather than just being a ghost.
