### ISSUE TITLE
Appveyor failing, can't find `Rcpp`

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/neotoma#206]
I'm not sure what I can do if this is a problem with appveyor of something in my code.  @sckott, the appveyor instance is running out of your account.  Is this something I can fix in my code, or something you need to fix?

**Comment by sckott** [comment]
i'll have a look..

**Comment by sckott** [comment]
see also https://github.com/krlmlr/r-appveyor/issues/70

**Comment by sckott** [comment]
just restarted will see what happens

**Comment by sckott** [comment]
still getting same problem, will check again soon

**Comment by SimonGoring** [comment]
This problem seems to be resolved.  Is it something you fixed @sckott?  I'm closing the issue for now.

**Comment by sckott** [comment]
@SimonGoring no, didn't do anything

**Comment by SimonGoring** [comment]
We're back to failing again [here](https://ci.appveyor.com/project/sckott/neotoma/build/1.0.876).

**Comment by SimonGoring** [comment]
And passing. . . I'm just going to ignore this from now on.  It seems to clean itself up & isn't a `neotoma` package issue.
