### ISSUE TITLE
Specifying chronology number in `write_agefile` has no effect.

### ISSUE THREAD

**Issue by andydawson** [ropensci/neotoma#210]
When there are multiple chronologies, passing chronology=2 versus chronology=1 to `write_agefile` makes no difference.

**Comment by andydawson** [comment]
I see where the problem is. When `get_chroncontrol` is called with a download object it only returns one chronology.

This happens in lines 57-58 of `write_agefile`:
`chron.controls <- get_chroncontrol(download, verbose = FALSE)`

Ideas?

**Comment by SimonGoring** [comment]
This is now resolved with PR #211.

**Comment by SimonGoring** [comment]
Sorry, didn't mean to reopen.
