### ISSUE TITLE
get_site(loc) isn't spatially bounded

### ISSUE THREAD

**Issue by IceAgeEcologist** [ropensci/neotoma#212]
get_site() doesn't seem to be working with the bounding box.

For example, 
demo_boxsearch_sites <- get_site(loc = c(-88, 25, -79, 30)) 
demo_boxsearch_sites <- get_site(loc = c(5,5,20,20)) 

both return a global suite of >8000 records from Neotoma

**Comment by SimonGoring** [comment]
That's really interesting.  It seems to be an API side issue and should be raised with @spatialit.  I'll add it.  You can use `get_dataset` with the `loc` parameter  and no flag for `datasettype` if that helps.

**Comment by spatialit** [comment]
This was fixed a few weeks ago. Going through GitHub comments today. I don't see any option for me to close this issue.

**Comment by gavinsimpson** [comment]
@spatialit As neotoma is in the ropensci account, only those users with special permissions can do admin-things. I'm sure @SimonGoring will close this when he has a chance.

**Comment by SimonGoring** [comment]
Closing the issue.
