### ISSUE TITLE
get_download.dataset_list function not found

### ISSUE THREAD

**Issue by jessicablois** [ropensci/neotoma#222]
A function (get_download.dataset_list) is listed in the function files, but not found. Example code:

> neotoma_datasets_list<- get_dataset(ageold = max_time, ageyoung = min_time, loc = c(-179.9, 0, -45, 89.9), datasettype = "vertebrate fauna")

> taxon_data <- get_download.dataset_list(neotoma_datasets_list)
Error in get_download.dataset_list(neotoma_datasets_list) : 
  could not find function "get_download.dataset_list"

**Comment by jessicablois** [comment]
Though perhaps this function is not necessary, since the simpler function "get_download" works on a dataset_list?

**Comment by SimonGoring** [comment]
Yes, that is the standard way of showing that there is a ‘get_download’ method for ‘dataset_list’.  The function recognizes that there is a ‘dataset_list’ being passed.
