### ISSUE TITLE
Get neotoma up onto cran

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/neotoma#60]
Not sure what needs to be done for unit testing. but:
- [x] Unit tests need to be completed
- [x] Bug fixes need to be completed
- [x] Other (non-essential?) cleanup needs to be undertaken
- [x] Documentation needs to be proofread

**Comment by SimonGoring** [comment]
I think this is all cleared up, except for the issues between Travis and Appveyor as indicated in issue #160.

**Comment by gavinsimpson** [comment]
We've still got issues.

 * [ ] need to make `gp.table` be a sysdata object and not use `data(gp.table()` in the code/function,
 * [ ] need to wrap the text/code in the example for `get_download()` in particular this line which `R CMD check` is complaining about

         Rd file 'get_download.Rd':
         \examples lines wider than 100 characters:
         t8kyr.datasets <- get_dataset(taxonname='*Pseudotsuga*', loc=c(-150, 40, -120, 60), ageold=20000, ageyoung=10000)
 * [] still a note about non-ASCII characters in data (presume it means `gp.table`?)

**Comment by SimonGoring** [comment]
I'll go through these.  It's dinner & family time now.

**Comment by gavinsimpson** [comment]
@SimonGoring you can delicate remember! Add an issue for each outstanding problem and allocate someone to fix it. Worst that can happen is that said person declines. I've held off doing anything of late as you been touching the code base all over and I wasn't sure what you were and weren't working on.

**Comment by SimonGoring** [comment]
I'm the king of this castle and I'll do what I want! :)

Just pinged you on the extractor stuff.  I don't think it's the gp.table that's the problem, I think it's things like isoetes that get pinged, but I'll try to track it down.  The gp.table is a list of country names.

**Comment by gavinsimpson** [comment]
`gp.table` is a separate issue from the non-ASCII strings; you shouldn't be doing `data(foo)` in R function code in packages now. You need `sysdata` for that.

**Comment by SimonGoring** [comment]
Okay, I'll look into `sysdata`.

**Comment by SimonGoring** [comment]
Just to clarify this, I need to put the tables into a sysdata.rda file,
right?  The one issue I'm concerned with is that while `gp.table` does not
need to be discoverable (and can exist hidden from the user), the
compile_taxon table should be able to be seen using a `data` call.  I think
people should be able to know what's been compressed.  Maybe that's just a
matter of making a new extraction function if data's been compressed.
That's probably a better solution actually, then I'll just stick the
variable in `sysdata.rda` as well.

But to be clear, if I have two tables, `data1` and `data2` I'm just going
to save them using `save(data1, data2, file=data/sysdata.rda)`, right?

**Comment by SimonGoring** [comment]
Okay, I've cleared up the sysdata/`data` issue.  Finished with commit https://github.com/ropensci/neotoma/commit/87ad4ad5bea9b0aafafec0d3102c412738ae3646.  Just the ASCII issues left now.

**Comment by SimonGoring** [comment]
It looks like the non-ASCII characters error is resolved.  Not sure where that happened, I'm trolling through the logs but haven't found it yet.

**Comment by SimonGoring** [comment]
Alright.  Right now it looks like everything is cleared up.  I've updated my local R version and am running the checks right now, but things all seem to be passing.  The last outstanding issue is the Appveyor and Travis problem (Issue #160) but these problems seem to be tied to the tests.

Given that all tests pass locally and we're not getting flagged for any Errors, warnings or notes, I'm going to try to release the package using `devtools::release()`.  I'm just doing some finishing touches.

**Comment by SimonGoring** [comment]
So, things are running on Linux according to Travis, I don't know if @gavinsimpson needs to compile, but is certainly welcome to.  There are two notes that seem to remain in the Travis build, and I'm not sure how to resolve them.  Are these critical issues @karthik or @gavinsimpson? or will CRAN accept the build as is?

**Comment by gavinsimpson** [comment]
@SimonGoring Those two NOTEs are fine. The first you'll always get with `--as-cran` as it just flags up the maintainer and the licence of the package as a quick check for the CRAN bods. The second is just a Travis config issue - the system doesn't seem configured with a library location or repository so the package dependency checks haven't been completed there fully. This will go away on CRAN when they test.

I've compiled and checked under R 3-2-patched and R-Devel and I am seeing no issues either. If you aren't seeing anything at your end, Win Builder isn't seeing anything, then you are ready to brave the CRAN folk with **neotoma**.

**Comment by SimonGoring** [comment]
We're up on CRAN so I'm going to close this.  Thanks everyone!

**Comment by sckott** [comment]
:rocket:
